const express = require('express');
const router = express.Router();
const { adminController } = require('../controllers');
const { authenticate, authorize } = require('../middlewares/auth');
const { validateSystemConfig, validateGSTConfig } = require('../utils/validators');
router.use(authenticate);
router.use(authorize('admin'));
router.get('/dashboard', adminController.getDashboard);
router.get('/health', adminController.getSystemHealth);
router.get('/reports/sales', adminController.getSalesReport);
router.get('/reports/inventory', adminController.getInventoryReport);
router.get('/reports/customers', adminController.getCustomerReport);
router.get('/reports/top-products', adminController.getTopProducts);
router.get('/reports/frequently-bought', adminController.getFrequentlyBoughtProducts);
router.get('/reports/low-stock', adminController.getLowStockProducts);
router.get('/logs', adminController.getAdminLogs);
router.get('/config', adminController.getSystemConfig);
router.put('/config', validateSystemConfig, adminController.updateSystemConfig);
router.get('/gst-config', adminController.getGSTConfig);
router.put('/gst-config/:id', validateGSTConfig, adminController.updateGSTConfig);
router.get('/stats/business', adminController.getBusinessStats);
router.get('/stats/pending-orders', adminController.getPendingOrdersCount);
router.get('/activity/recent', adminController.getRecentActivity);
router.get('/export/:type', adminController.exportData);
module.exports = router;
