const express = require('express');
const router = express.Router();
const { authController } = require('../controllers');
const { authenticate, optionalAuth } = require('../middlewares/auth');
const { otpLimiter, loginLimiter } = require('../middlewares/rateLimiter');
const { validateSendOTP, validateVerifyOTP, validateRegister, validateAdminLogin, validateRefreshToken } = require('../utils/validators');
router.post('/otp/send', otpLimiter, validateSendOTP, authController.sendOTP);
router.post('/otp/send-by-email', otpLimiter, authController.sendOTPByEmail);
router.post('/otp/verify', loginLimiter, validateVerifyOTP, authController.verifyOTP);
router.post('/otp/resend', otpLimiter, validateSendOTP, authController.resendOTP);
router.post('/register', validateRegister, authController.register);
router.post('/admin/login', loginLimiter, validateAdminLogin, authController.adminLogin);
router.post('/admin/verify-otp', loginLimiter, authController.adminVerifyOTP);
router.post('/refresh', validateRefreshToken, authController.refreshToken);
router.post('/logout', authenticate, authController.logout);
router.post('/logout-all', authenticate, authController.logoutAll);
router.get('/me', authenticate, authController.getMe);
router.put('/me', authenticate, authController.updateMe);
router.put('/change-password', authenticate, authController.changePassword);
module.exports = router;