const express = require('express');
const router = express.Router();
const { cartController } = require('../controllers');
const { authenticate, authorize } = require('../middlewares/auth');
const { validateAddToCart, validateUpdateCartItem } = require('../utils/validators');
router.use(authenticate);
router.use(authorize('retail_customer', 'wholesale_customer'));
router.get('/', cartController.getCart);
router.post('/items', validateAddToCart, cartController.addItem);
router.put('/items/:productId', validateUpdateCartItem, cartController.updateItem);
router.delete('/items/:productId', cartController.removeItem);
router.delete('/', cartController.clearCart);
router.post('/sync-prices', cartController.syncPrices);
router.post('/sync-all', cartController.syncAll);
router.get('/validate', cartController.validateCart);
module.exports = router;