const express = require('express');
const router = express.Router();
const { categoryController } = require('../controllers');
const { authenticate, authorize, optionalAuth } = require('../middlewares/auth');
const { validateCreateCategory, validateUpdateCategory } = require('../utils/validators');
router.get('/', optionalAuth, categoryController.getAllCategories);
router.get('/:id', optionalAuth, categoryController.getCategoryById);
router.get('/:id/products', optionalAuth, categoryController.getCategoryProducts);
router.use(authenticate);
router.use(authorize('admin'));
router.get('/admin/all', categoryController.getAllCategoriesAdmin);
router.post('/', validateCreateCategory, categoryController.createCategory);
router.put('/:id', validateUpdateCategory, categoryController.updateCategory);
router.delete('/:id', categoryController.deleteCategory);
router.put('/:id/toggle-active', categoryController.toggleActive);
module.exports = router;