const express = require('express');
const router = express.Router();
const { invoiceController } = require('../controllers');
const { authenticate, authorize } = require('../middlewares/auth');
const { validateMarkAsPaid } = require('../utils/validators');
router.use(authenticate);
router.get('/my-invoices', authorize('retail_customer', 'wholesale_customer'), invoiceController.getMyInvoices);
router.get('/reports/revenue', authorize('admin'), invoiceController.getRevenueReport);
router.get('/reports/gst', authorize('admin'), invoiceController.getGSTReport);
router.get('/reports/pending', authorize('admin'), invoiceController.getPendingPayments);
router.get('/', authorize('admin'), invoiceController.getAllInvoices);
router.get('/number/:invoiceNumber', invoiceController.getInvoiceByNumber);
router.get('/order/:orderId', invoiceController.getInvoiceByOrder);
router.get('/:id', invoiceController.getInvoice);
router.get('/:id/download', invoiceController.downloadInvoice);
router.put('/:id/paid', authorize('admin'), validateMarkAsPaid, invoiceController.markAsPaid);
module.exports = router;