const express = require('express');
const router = express.Router();
const { productController } = require('../controllers');
const { authenticate, authorize, optionalAuth } = require('../middlewares/auth');
const { uploadExcel } = require('../middlewares/upload');
const { validateCreateProduct, validateUpdateProduct, validateStockUpdate } = require('../utils/validators');
router.get('/', optionalAuth, productController.getAllProducts);
router.get('/search', optionalAuth, productController.searchProducts);
router.get('/:id/frequently-bought-together', optionalAuth, productController.getFrequentlyBoughtTogether);
router.get('/:id', optionalAuth, productController.getProductById);
router.use(authenticate);
router.use(authorize('admin'));
router.get('/admin/all', productController.getAllProductsAdmin);
router.get('/admin/low-stock', productController.getLowStockProducts);
router.post('/', validateCreateProduct, productController.createProduct);
router.put('/:id', validateUpdateProduct, productController.updateProduct);
router.delete('/:id', productController.deleteProduct);
router.put('/:id/stock', validateStockUpdate, productController.updateStock);
router.put('/:id/toggle-active', productController.toggleActive);
router.post('/bulk-upload', uploadExcel, productController.bulkUpload);
router.get('/template/download', productController.downloadTemplate);
module.exports = router;
